require 'pry'

def game_hash
  stats = { :home => { :team_name => {}, 
    :colors => {}, 
    :players => [
        {:player_name => "", 
          :number => , 
          :shoe => , 
          :points => , 
          :rebounds => , 
          :rebounds => , 
          :assists => , 
          :steals => , 
          :blocks => , 
          :slam_dunks => 
        },
        {:player_name => "", 
          :number => , 
          :shoe => , 
          :points => , 
          :rebounds => , 
          :rebounds => , 
          :assists => , 
          :steals => , 
          :blocks => , 
          :slam_dunks => 
        },
        {:player_name => "", 
          :number => , 
          :shoe => , 
          :points => , 
          :rebounds => , 
          :rebounds => , 
          :assists => , 
          :steals => , 
          :blocks => , 
          :slam_dunks => 
        },
        {:player_name => "", 
          :number => , 
          :shoe => , 
          :points => , 
          :rebounds => , 
          :rebounds => , 
          :assists => , 
          :steals => , 
          :blocks => , 
          :slam_dunks => 
        },
        {:player_name => "", 
          :number => , 
          :shoe => , 
          :points => , 
          :rebounds => , 
          :rebounds => , 
          :assists => , 
          :steals => , 
          :blocks => , 
          :slam_dunks => 
        }
        ]
    },
    :away => { :team_name => {}, 
      :colors => {}, 
      :players => [
        {:player_name => "", 
          :number => , 
          :shoe => , 
          :points => , 
          :rebounds => , 
          :rebounds => , 
          :assists => , 
          :steals => , 
          :blocks => , 
          :slam_dunks => 
        },
        {:player_name => "", 
          :number => , 
          :shoe => , 
          :points => , 
          :rebounds => , 
          :rebounds => , 
          :assists => , 
          :steals => , 
          :blocks => , 
          :slam_dunks => 
        },
        {:player_name => "", 
          :number => , 
          :shoe => , 
          :points => , 
          :rebounds => , 
          :rebounds => , 
          :assists => , 
          :steals => , 
          :blocks => , 
          :slam_dunks => 
        },
        {:player_name => "", 
          :number => , 
          :shoe => , 
          :points => , 
          :rebounds => , 
          :rebounds => , 
          :assists => , 
          :steals => , 
          :blocks => , 
          :slam_dunks => 
        },
        {:player_name => "", 
          :number => , 
          :shoe => , 
          :points => , 
          :rebounds => , 
          :rebounds => , 
          :assists => , 
          :steals => , 
          :blocks => , 
          :slam_dunks => 
        }
        ]
  }
